[package]
name = "access-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[dependencies]
rss-request-context.workspace = true
uuid.workspace = true
thiserror.workspace = true
tokio.workspace = true
argon2.workspace = true
rand_core.workspace = true
zeroize.workspace = true
[lints]
workspace = true
