[package]
name = "rss-identity-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[dependencies]
rand_core.workspace = true
rss-identity-core.workspace = true
rss-contract.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
tokio.workspace = true
sqlx = { workspace = true, features = ["uuid", "json"] }
rss-request-context.workspace = true
rss-transactional-messaging.workspace = true
rss-transactional-messaging-postgres.workspace = true
futures = "0.3"
zeroize.workspace = true
url = "2.5"
thiserror.workspace = true
[dev-dependencies]
anyhow.workspace = true
rss-contract.workspace = true
rss-transactional-messaging-postgres = { workspace = true, features = ["integration"] }
sqlx = { workspace = true, features = ["uuid", "json"] }
tokio.workspace = true
[lints]
workspace = true
