GRANT USAGE ON SCHEMA identity_authority TO {role};
GRANT SELECT ON identity_authority.schema_version TO {role};
GRANT SELECT ON identity_authority.deployment TO {role};
GRANT SELECT,UPDATE ON identity_authority.guard TO {role};
GRANT SELECT,INSERT,UPDATE ON identity_authority.accounts TO {role};
GRANT SELECT,INSERT,UPDATE ON identity_authority.memberships TO {role};
GRANT SELECT,INSERT,UPDATE ON identity_authority.local_credentials TO {role};
GRANT SELECT,INSERT,UPDATE,DELETE ON identity_authority.attempts TO {role};
GRANT SELECT,INSERT,UPDATE ON identity_authority.sessions TO {role};
GRANT SELECT,INSERT,UPDATE ON identity_authority.providers TO {role};
GRANT SELECT,INSERT,UPDATE ON identity_authority.provider_credentials TO {role};
GRANT SELECT,INSERT,UPDATE ON identity_authority.external_identities TO {role};
GRANT SELECT,INSERT,UPDATE,DELETE ON identity_authority.link_intents TO {role};
GRANT SELECT,INSERT,UPDATE,DELETE ON identity_authority.oidc_transactions TO {role};
GRANT USAGE ON SCHEMA rss_transactional_messaging TO {role};
GRANT SELECT ON rss_transactional_messaging.policy TO {role};
GRANT SELECT,INSERT ON rss_transactional_messaging.outbox TO {role};
GRANT USAGE ON SEQUENCE rss_transactional_messaging.outbox_seq_seq TO {role};
GRANT EXECUTE ON FUNCTION rss_transactional_messaging.check_execution() TO {role};
